CREATE TABLE IF NOT EXISTS Utilisateur (
pseudo VARCHAR(30) PRIMARY KEY,
nom VARCHAR(30),
prenom VARCHAR(30),
mail VARCHAR(50),
mdp VARCHAR(100));

CREATE TABLE IF NOT EXISTS Sujet (
idSujet INTEGER(5) PRIMARY KEY AUTO_INCREMENT,
libelle VARCHAR(50),
dateCreation DATE,
createur VARCHAR(30) REFERENCES Utilisateur(pseudo) ON DELETE CASCADE); 

CREATE TABLE IF NOT EXISTS Message (
idMessage INTEGER(5) PRIMARY KEY AUTO_INCREMENT,
contenu VARCHAR(255),
idSujet INTEGER(5) REFERENCES Sujet(idSujet) ON DELETE CASCADE,
createur VARCHAR(30) REFERENCES Utilisateur(pseudo) ON DELETE CASCADE);

